* moved configuration constants and quote_words() function from cheaplab   sources to LogDevice/cheaplab. * renamed package.preinst to module.preinst

diff --git a/cheaplab/logdevicedctl b/cheaplab/logdevicedctl
--- a/cheaplab/logdevicedctl
+++ b/cheaplab/logdevicedctl
@@ -9,11 +9,59 @@ declare -r PIDFILE=/run/logdeviced.pid
 declare -r timeout=${2-60}
 declare -r deadline=$(($(date +%s)+$timeout))
 
-source ${LAB_PACKAGES_ROOT?}/cheaplib/current/cheaplib.sh || exit 1
+for inc in this config; do
+    source ${LAB_MODULES_ROOT?}/cheaplib/current/$inc.sh || exit 1
+done
+
+
+# Output a Zookeeper URL zk://<ip:port>{,<ip:port>} containing the
+# list of internal ip addresses of all EC2 instances in the specified
+# (Zookeeper) cluster. <port> is the 'port:' setting in the cluster
+# config file on the node.  Default is 2181. ZK clients can use this
+# URL to contact the Zookeeper ensemble. If the cluster does not exist
+# or is empty, output an empty string. On error return a non-zero status.
+#
+# @param  $1   cluster   cluster id of Zookeeper cluster
+# @param  $2   region    (optional) region to query for $cluster. If not set,
+#                        the local region will be used.
+zookeeper_url() {
+    declare -r cluster=$1
+    local region=${2-}
+
+    [[ -n $region ]] || region=$(LAB-this_region) || return
+
+    local port
+    port=$(LAB-get_cluster_attribute $cluster "port" 2181)
+    if [[ $? -ne 0 ]]; then
+	>&2 echo "ERROR: failed to get Zookeeper port number for"\
+	    "cluster $cluster"
+	return 1
+    fi
+
+    local ips
+    ips=$(aws ec2 describe-instances                                       \
+	--filters "Name=tag:cheaplab-cluster,Values=$cluster"              \
+     'Name=instance-state-name,Values=running,starting,stopping,stopped'   \
+	--query "Reservations[].Instances[].[PrivateIpAddress]"            \
+	--region $region                                                   \
+	--output text) || return 1
+
+    [[ $ips ]] || return 0
+
+    echo -n "zk:"
+
+    local ip
+    local sep=
+    for ip in $ips; do
+	echo -n ${sep}$ip:$port
+	sep=,
+    done
+}
+
 
 case "${1-}" in
    start)
-     for v in LAB_PACKAGES_ROOT LAB_DATADIR LAB_PORT_PROMETHEUS_SCRAPE LAB_ARGS;
+     for v in LAB_MODULES_ROOT LAB_DATADIR LAB_PORT_PROMETHEUS_SCRAPE LAB_ARGS;
      do
 	 if [[ -z ${!v+_} ]]; then
 	     >&2 echo "ABORT: $v is not set in the environment."\
@@ -26,26 +74,26 @@ case "${1-}" in
        exit 1
      fi
 
-     CURRENT_PACKAGE=$LAB_PACKAGES_ROOT/logdeviced/current
-     if [[ ! -h $CURRENT_PACKAGE ]]; then
-       >&2 echo "ERROR: $CURRENT_PACKAGE does not exist or not a symlink"
+     CURRENT_MODULE=$LAB_MODULES_ROOT/logdeviced/current
+     if [[ ! -h $CURRENT_MODULE ]]; then
+       >&2 echo "ERROR: $CURRENT_MODULE does not exist or not a symlink"
        exit 1
      fi
-     cd $CURRENT_PACKAGE 2>/dev/null
+     cd $CURRENT_MODULE 2>/dev/null
      if [[ $? -ne 0 ]]; then
        >&2 echo "ERROR: failed to cd to current package directory"\
-                $(readlink -m $CURRENT_PACKAGE)
+                $(readlink -m $CURRENT_MODULE)
        exit 1
      fi
      if [[ ! -x bin/logdeviced ]]; then
-       >&2 echo "ERROR: $CURRENT_PACKAGE/bin/logdeviced not found"\
+       >&2 echo "ERROR: $CURRENT_MODULE/bin/logdeviced not found"\
                 "or not executable"
        exit 1
      fi
 
      region=$(LAB-this_region) || exit
 
-     zk=$(LAB-zookeeper_url $ZK $region) || exit
+     zk=$(zookeeper_url $ZK $region) || exit
      if [[ -z $zk ]]; then
 	 >&2 echo "No nodes found for Zookeeper cluster $ZK"
 	 exit 1
